[package]
name = "days_left_until"
version = "0.1.0"
authors = ["yidmoussi <youssef.idmoussi@avaliance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
